# For detailed configuration reference documentation, visit:
# https://supabase.com/docs/guides/local-development/cli/config
# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "CREvolt-Tenant"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public"]
max_rows = 100

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000", "http://localhost:54321/auth/v1/callback"]
jwt_expiry = 36000

[db]
port = 54322

[studio]
port = 54323

# [auth.external.google]
# enabled = true
# client_id = "env(GOOGLE_CLIENT_ID)"
# secret = "env(GOOGLE_SECRET)"
# redirect_uri = "http://localhost:54321/auth/v1/callback"

[auth.email]
double_confirm_changes = true
enable_confirmations = true
enable_signup = true

# [auth.email.smtp]
# enabled = true
# host = "smtp.resend.com"
# port = 587
# user = "resend"
# pass = "env(RESEND_API_KEY)"
# admin_email = "noreply@mail.crevolt.com"
# sender_name = "Crevolt"

# [auth.hook.send_email]
# enabled = true
# uri = "http://127.0.0.1:54321/functions/v1/send-email"
# secrets = "env(SEND_EMAIL_HOOK_SECRET)"

# [auth.email.template.confirmation]
# subject = "Confirm your email"
# content_path = "supabase/templates/confirm-mail.html"

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"

# RIGHT NOW , THE MAIL IS TURNED OFF USING THE CUSTOM EMIAL
